# Generated by Django 2.0.6 on 2018-06-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
